<?php


/**
 * This class adds structure of 'anketo_detail_mapping' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 03/02/16 11:30:28
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class AnketoDetailMappingMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.AnketoDetailMappingMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(AnketoDetailMappingPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(AnketoDetailMappingPeer::TABLE_NAME);
		$tMap->setPhpName('AnketoDetailMapping');
		$tMap->setClassname('AnketoDetailMapping');

		$tMap->setUseIdGenerator(true);

		$tMap->addForeignKey('DETAIL_ID', 'DetailId', 'INTEGER', 'anketo_category_name', 'ID', true, null);

		$tMap->addForeignKey('COMMON_ID', 'CommonId', 'INTEGER', 'anketo_common_name', 'COMMON_ID', true, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

	} // doBuild()

} // AnketoDetailMappingMapBuilder
