<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/03/02 11:53:07

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:host=localhost;dbname=anketo',
  'username' => 'root',
  'password' => 'root',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
